name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: build 1.16
      run: |
        cd CupEdition-1.16
        chmod +x gradlew
        ./gradlew build
        cd ..
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BH-CupEdition
        path: build/libs/bleachhack-cupedition-1.3.jar
    
        
